# Generated by Django 4.1.5 on 2023-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_police_app', '0002_signupmodels_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodels',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
