# Generated by Django 4.1.5 on 2023-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_police_app', '0003_alter_signupmodels_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='complationmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('complaintdate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactusmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='emergencyinformationmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('address', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='firmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('firdate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='givefeedbackmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='searchpolicestationmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('policestationname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='visitormodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('visitdate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='signupmodels',
            name='mobile',
            field=models.BigIntegerField(default=78945613),
        ),
    ]
