# Generated by Django 4.1.5 on 2023-03-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_police_app', '0004_complationmodels_contactusmodels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyinformationmodels',
            name='file',
            field=models.FileField(upload_to='upload'),
        ),
    ]
